/**
 * Copyright 2025 Simpleway Europe a.s.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { createRequestId, INnounceClientRequestEvent } from "../INnounceClientRequestEvent.ts";

/**
 * The `DesignLoadEvent` interface represents an event that is sent to load a design.
 *
 * Extends:
 * - `INnounceClientRequestEvent`: Specifies that this event conforms to the client request event
 *   structure and inherits its properties.
 */
export interface DesignLoadEvent extends INnounceClientRequestEvent {}

/**
 * Creates and returns a new DesignLoadEvent object.
 *
 * The returned object includes a 'type' property set to "designLoadEvent"
 * and a unique 'requestId' generated by the createRequestId function.
 *
 * @return {DesignLoadEvent} A new DesignLoadEvent object containing event type and request ID.
 */
export function createDesignLoadEvent(): DesignLoadEvent {
	return {
		type: "designLoadEvent",
		requestId: createRequestId(),
	};
}
